apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  labels:
    external-secrets.io/component: controller
  name: basicauths.generators.external-secrets.io
spec:
  group: generators.external-secrets.io
  names:
    categories:
    - external-secrets
    - external-secrets-generators
    kind: BasicAuth
    listKind: BasicAuthList
    plural: basicauths
    singular: basicauth
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: |-
          BasicAuth generates a random basic auth based on the
          configuration parameters in spec.
          You can specify the length, characterset and other attributes.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: BasicAuthSpec controls the behavior of the basic auth generator.
            properties:
              password:
                description: PasswordSpec controls the behavior of the password generator.
                properties:
                  allowRepeat:
                    default: false
                    description: set AllowRepeat to true to allow repeating characters.
                    type: boolean
                  digits:
                    description: |-
                      Digits specifies the number of digits in the generated
                      password. If omitted it defaults to 25% of the length of the password
                    type: integer
                  encoding:
                    default: raw
                    description: |-
                      Encoding specifies the encoding of the generated password.
                      Valid values are:
                      - "raw" (default): no encoding
                      - "base64": standard base64 encoding
                      - "base64url": base64url encoding
                      - "base32": base32 encoding
                      - "hex": hexadecimal encoding
                    enum:
                    - base64
                    - base64url
                    - base32
                    - hex
                    - raw
                    type: string
                  length:
                    default: 24
                    description: |-
                      Length of the password to be generated.
                      Defaults to 24
                    type: integer
                  noUpper:
                    default: false
                    description: Set NoUpper to disable uppercase characters
                    type: boolean
                  symbolCharacters:
                    description: |-
                      SymbolCharacters specifies the special characters that should be used
                      in the generated password.
                    type: string
                  symbols:
                    description: |-
                      Symbols specifies the number of symbol characters in the generated
                      password. If omitted it defaults to 25% of the length of the password
                    type: integer
                required:
                - allowRepeat
                - length
                - noUpper
                type: object
              username:
                description: UsernameSpec controls the behavior of the username generated.
                properties:
                  includeNumbers:
                    default: false
                    description: set IncludeNumbers to add 4 numbers at the end of
                      the username after the sufix.
                    type: boolean
                  length:
                    default: 8
                    description: |-
                      Length of each word of the username to be generated.
                      Defaults to 8
                    type: integer
                  prefix:
                    description: |-
                      Prefix specifies a prefix to be added to the generated
                      username. If omitted it defaults to empty
                    type: string
                  separator:
                    description: |-
                      Separator specifies the separator character that should be used
                      in the generated username. If omitted it defaults to "_"
                    type: string
                  sufix:
                    description: |-
                      Sufix specifies a sufix to be added to the generated
                      username. If omitted it defaults to empty
                    type: string
                  wordCount:
                    default: 1
                    description: |-
                      WordCount specifies the number of words in the generated
                      username. If omitted it defaults to 1
                    type: integer
                required:
                - includeNumbers
                - length
                type: object
            type: object
          status:
            description: GeneratorStatus represents the status of a generator.
            properties:
              output:
                x-kubernetes-preserve-unknown-fields: true
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
