replicaCount: 1
image:
  repository: ingeingero/external-secrets
  pullPolicy: IfNotPresent
  # -- The image tag to use. The default is the chart appVersion.
  tag: "mylatest"
# -- If set, install and upgrade CRDs through helm chart.
installCRDs: false