apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  controller: dev
  provider:
    # awssm:
    #   auth:
    #     secretRef:
    #       accessKeyIDSecretRef:
    #         name: awssm-secret
    #         key: access-key

    #       secretAccessKeySecretRef:
    #         name: awssm-secret
    #         key: secret-access-key

    #   role: iam-role
    #   region: eu-central-1
      gcpsm:
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: gcpsm-secret
              key: secret-access-credentials
        projectID: myproject