{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "external-secrets.fullname" . }}-network-policy
  namespace: {{ include "external-secrets.namespace" . }}
spec:
  egress:
    {{- with .Values.networkPolicy.egress }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  ingress:
    {{- with .Values.networkPolicy.ingress }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  podSelector:
    matchLabels:
      {{- include "external-secrets.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
  - Ingress
{{- end }}
