{{- if and .Values.webhook.create .Values.webhook.certManager.enabled .Values.webhook.certManager.cert.create .Values.webhook.certManager.cert.createIssuer }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: '{{ include "external-secrets.name" . }}-selfsigned-issuer'
  namespace: {{ template "external-secrets.namespace" . }}
  labels:
    {{- include "external-secrets-webhook.labels" . | nindent 4 }}
    external-secrets.io/component: webhook
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: '{{ include "external-secrets.name" . }}-root-cert'
  namespace: {{ template "external-secrets.namespace" . }}
  labels:
    {{- include "external-secrets-webhook.labels" . | nindent 4 }}
    external-secrets.io/component: webhook
spec:
  isCA: true
  commonName: 'ca.webhook.{{ include "external-secrets.name" . }}'
  secretName: '{{ include "external-secrets.name" . }}-root-cert'
  duration: "48300h0m0s"
  issuerRef:
    name: '{{ include "external-secrets.name" . }}-selfsigned-issuer'
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: {{ .Values.webhook.certManager.cert.issuerRef.kind }}
metadata:
  name: "{{ .Values.webhook.certManager.cert.issuerRef.name }}"
  namespace: {{ template "external-secrets.namespace" . }}
  labels:
    {{- include "external-secrets-webhook.labels" . | nindent 4 }}
    external-secrets.io/component: webhook
spec:
  ca:
    secretName: '{{ include "external-secrets.name" . }}-root-cert'
{{- end }}