apiVersion: v2
name: external-secrets
description: External secret management for Kubernetes
type: application
version: "0.1.1"
appVersion: "0.1.0"
kubeVersion: ">= 1.11.0"
keywords:
  - kubernetes-external-secrets
  - secrets
home: https://github.com/external-secrets/external-secrets
maintainers:
  - name: mcavoyk
    email: kellinmcavoy@gmail.com
