apiVersion: v2
name: external-secrets
description: External secret management for Kubernetes
type: application
version: "0.4.2"
appVersion: "v0.4.2"
kubeVersion: ">= 1.11.0-0"
keywords:
  - kubernetes-external-secrets
  - secrets
home: https://github.com/external-secrets/external-secrets
icon: https://raw.githubusercontent.com/external-secrets/external-secrets/main/assets/round_eso_logo.png
maintainers:
  - name: mcavoyk
    email: kellinmcavoy@gmail.com
